apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
{{ include "airflow.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
    - pods
    - services
  verbs: ["create", "get", "delete", "list", "watch"]
- apiGroups: [""]
  resources:
   - "pods/log"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
    - "pods/exec"
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ['{{ include "airflow.fullname" . }}-secrets']
  verbs: ["patch", "get"]