apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
{{ include "airflow.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "airflow.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "airflow.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}