apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
   - port: {{ .Values.postgres.service.port }}
  selector:
    app: postgres
