apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-web
  labels:
{{ include "airflow.labels" . | indent 4 }}
spec:
  type: {{ .Values.airflow.service.type }}
  ports:
    - port: {{ .Values.airflow.service.port }}
      targetPort: http
      protocol: TCP
      name: "airflow-web-http"
  selector:
    app: web
